# Uncomment the next line to define a global platform for your project
platform :ios, '15.6'

def shared_pods
  use_frameworks!
  pod 'GoogleMLKit/BarcodeScanning', '8.0.0'
  pod 'Firebase/Messaging'
end

target 'User' do
  shared_pods
end

target 'Agent' do
  shared_pods
end

target 'Admin' do
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end

  # 프로젝트 레벨에서도 샌드박스 비활성화
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
  end
end
